-- 1
USE Company_SD
SELECT D.Dnum, D.Dname, E.Fname+' '+E.Lname
	FROM DEPARTMENTS D 
INNER JOIN EMPLOYEE E
	ON D.MGRSSN = E.SSN

-- 2
SELECT D.DNAME , P.PNAME 
	FROM DEPARTMENTS D
INNER JOIN PROJECT P
	ON D.DNUM = P.DNUM

-- 3 
SELECT * , E.FNAME + ' ' + E.LNAME AS EMP
	FROM Dependent D
LEFT JOIN EMPLOYEE E
	ON D.ESSN = E.SSN

-- 4 
SELECT PNUMBER, PNAME, PLOCATION, CITY
	FROM PROJECT
WHERE CITY IN ('CAIRO', 'ALEX')

-- 5
SELECT * FROM PROJECT
WHERE PNAME LIKE 'a%'

-- 6
SELECT * FROM EMPLOYEE 
WHERE DNO = 30 AND SALARY BETWEEN 1000 AND 2000

-- 7
SELECT E.FNAME , E.LNAME 
	FROM EMPLOYEE E
INNER JOIN WORKS_FOR W
	ON E.SSN = W.ESSn
INNER JOIN PROJECT P
	ON W.Pno = P.PNUMBER
WHERE E.DNO = 10 AND  W.HOURS >= 10 AND P.PNAME = 'AL RABWAH'

-- 8 
SELECT E.FNAME+' '+ E.LNAME [EMP NAMES]
	FROM EMPLOYEE E
INNER JOIN Employee E2
	ON E2.SUPERSSN = E.SUPERSSN
WHERE E2.FNAME = 'KAMEL' AND E2.LNAME = 'MOHAMED'

-- 9

SELECT E.FNAME+' '+E.LNAME AS EMPLOYEE_NAME, P.PNAME AS PROJECT_NAME
	FROM EMPLOYEE E
LEFT JOIN Works_for W
	ON E.SSN = W.ESSn
LEFT JOIN PROJECT P
	ON W.Pno = P.PNUMBER
ORDER BY PROJECT_NAME

-- 10

SELECT P.PNUMBER, D.DNAME + ' ' + E.LNAME AS MGRNAME, E.ADDRESS, E.BDATE
FROM EMPLOYEE E
INNER JOIN WORKS_FOR W
ON E.SSN = W.ESSn
INNER JOIN PROJECT P
ON W.Pno = P.PNUMBER
INNER JOIN DEPARTMENTS D
ON P.DNUM = D.DNUM
WHERE D.MGRSSN = E.SSN

-- 11

SELECT * FROM EMPLOYEE E 
, DEPARTMENTS D 
WHERE D.MGRSSN = E.SSN

-- 12

SELECT * FROM EMPLOYEE, Dependent 
WHERE ESSN = SSN
AND Dependent_name is not null


--////// part 2 //////
-- 1
INSERT INTO Employee(Dno, SSN, Superssn, Salary) VALUES (30, 102672, 112233, 3000)
-- 2
INSERT INTO Employee(Dno, SSN) VALUES (30, 102660)
-- 3
update employee 
set salary = salary + ((salary * 25) / 100)